In [1]:
using JuMP, Gurobi
using CSV, LinearAlgebra, DataFrames
using Plots
using DelimitedFiles

In [2]:
#load social and ecological data and orgnize 
FL = repeat([Float64], inner=15)
dtype = append!([String], FL);

regional_EF = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/new_EF_SC1.csv",header=1,delim=",", types=dtype) |> DataFrame    
capacity = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/capacity2.csv",header=1,delim=",", types=dtype) |> DataFrame    
distance = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/distance.csv",header=1,delim=",") |> DataFrame 
LCA_model = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/LCA_model2.csv",header=1,delim=",") |> DataFrame 
D_Dsoc = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/D_Dsoc1.csv",header=1,delim=",") |> DataFrame
GDP = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/GDP.csv",header=1,delim=",") |> DataFrame;
emi_sink = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/SC_regional/emission_sink1.csv",header=1,delim=",") |> DataFrame;

In [23]:
cell_demand = 0.001*164.98*(1.369*1e6)*2           # annual demand of Li battery for tesla (1.369M EV/yr, ~2 NMC111 pack/EV, 164.98 kg/pack (35kwh/pack), 80~100 kWh per EV)

global_sink = 1.099e10                        # global pub (ocean) CO2 sequestration (ton/yr)
global_sink_tot = 2.236e10                  # global total (ocean+land) CO2 sequestration (ton/yr)
global_emi = 3.53e10                          # global CO2 emission (ton/yr)
global_gdp = 96882e9                          # 2021 global GDP ($/yr)
es_ratio = global_sink/global_emi
es_ratio_tot = global_sink_tot/global_emi
emission_c = emi_sink[!, "emission"]          # national CO2 emission (ton/yr)
sink_c = emi_sink[!, "sink ton/yr"]           # national CO2 sink (ton/yr)

# D = D_Dsoc[!, "D"]          # national CO2 emission (ton/yr)
Dsoc = D_Dsoc[!, "Dsoc ton/yr"]           # national CO2 sink (ton/yr)

EF_trans = 1.005/10000                        # ton CO2/km*ton (The average freight truck in the U.S. emits 161.8 grams of CO2 per ton-mile)
process = LCA_model[!,"process"]
countries = capacity[!,"country"]
ncty = size(countries,1)                          # No. of countries
nproc = size(process,1);                          # No. of processes 

mkt_loc = findfirst(isequal("United States"), countries)
mkt_proc = findfirst(isequal("battery"), process)

# seperate model
cathode = collect(1:4)
cell = collect(5:10)
noncell = [12,13]
battery = [11,14]
scaler = LCA_model[!,"scaler"]
price = LCA_model[!,"price (usd/ton product)"]
vGDP = GDP[!,"GDP usd"];

In [102]:
M = -5e7

-5.0e7

In [36]:
# penalty = 10000 # ton/yr
penalty = 5; # ton/yr

In [25]:
up_cath = scaler[1:4] * scaler[5] * scaler[11]
up_cell = scaler[5:10] * scaler[11]
cell_sef = scaler[11]
up_noncell = scaler[12:13] * scaler[14]
noncell_sef = scaler[14]
battery_sef = scaler[15];

In [27]:
ipt = vcat(up_cath, up_cell, cell_sef, up_noncell, noncell_sef, battery_sef) 
input_amount = ipt.* cell_demand

15-element Vector{Float64}:
  49670.291589732
  69512.470736544
  67696.846500888
  69382.78329114
 129687.44540400001
  72376.074329
   5239.896784
   1309.974196
  31111.887154999997
  60258.81301599999
 327493.549
   2258.5762
   1806.86096
 451715.24
 451715.24

In [153]:
D = [0.2, 0.5, 0.6, 0.7, 0.8, 0.9]

6-element Vector{Float64}:
 0.2
 0.5
 0.6
 0.7
 0.8
 0.9

### Solve subproblem to get dual $\pi$ and $\alpha$

In [254]:
function reformu_pi(e, col_idx, proc_idx, ls_cstr)
    pi_matrix = zeros(ncty, nproc)
    pi = [getdual(con) for con in ls_cstr]
    B = []
    for k in proc_idx
        append!(B, e*scaler[k]*ones(ncty))
    end
    pi = pi .* B
    pi = reshape(pi, ncty, size(proc_idx)[1])
    pi_matrix[:,col_idx] = sum(pi, dims=2)
    
    return pi_matrix
end

reformu_pi (generic function with 2 methods)

In [255]:
function subprob(x_hat, e)
    model = Model(Gurobi.Optimizer)
    set_silent(model)
    @variable(model, y[1:ncty, 1:ncty, 1:nproc] >= 0)
    @variable(model, s >= 0)

    # node output flow constraint
    cstr_op = [@constraint(model, sum(y[i,j,k] for j in 1:ncty) <= e*x_hat[i,k]) for k in 1:nproc for i in 1:ncty]

    # cathode LCA constraints (index=5)
    cstr_cth = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= e*x_hat[j,5]*scaler[k]) for k in cathode for j in 1:ncty]

    # cell LCA constraints (index=11)
    cstr_cell = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= e*x_hat[j,11]*scaler[k]) for k in cell for j in 1:ncty]

    # non cell LCA constraints (index=14)
    cstr_noncell = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= e*x_hat[j,14]*scaler[k]) for k in noncell for j in 1:ncty]

    # battery LCA constraints (index=15)
    cstr_battery = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= e*x_hat[j,15]*scaler[k]) for k in battery for j in 1:ncty]
    
    @constraint(model, cstr_alp, sum(y[i,mkt_loc,mkt_proc] for i in 1:ncty) + s >= cell_demand)
    for j in 1:ncty-1
        @constraint(model, sum(y[i,j,mkt_proc] for i in 1:ncty) == 0)
    end 
    
    
    #######################
#     tranD = Vector{AffExpr}(undef, ncty)
#     tranS= Vector{AffExpr}(undef, ncty)
#     for j in 1:ncty
#         arc_emi = 0
#         for i in 1:ncty
#             amount = sum(y[i,j,k] for k in 1:nproc)
#             arc_emi += (amount * distance[!, 2:end][i,j] * EF_trans)
#         end
#         tranD[j] = arc_emi
#         tranS[j] = arc_emi * (sink_c[j]/emission_c[j] + es_ratio)
#     end
    
    tranD = Vector{AffExpr}(undef, ncty)
    for j in 1:ncty
        arc_emi = 0
        for i in 1:ncty
            amount = sum(y[i,j,k] for k in 1:nproc)
            arc_emi += (amount * distance[!, 2:end][i,j] * EF_trans)
        end
        tranD[j] = arc_emi
    end
    
    
#     @objective(model, Min, sum(tranD-tranS) + s*penalty)
    @objective(model, Min, sum(tranD) + s*penalty)
    JuMP.optimize!(model)
    
    qy_hat = JuMP.objective_value(model)
    sub_y = JuMP.value.(y)
    sub_s = JuMP.value.(s)
    
    
    ####################### 
    op_pi = [getdual(con) for con in cstr_op]
    op_pi = reshape(op_pi, ncty, nproc)*e

    cth_pi = reformu_pi(e, 5, cathode, cstr_cth)
    cell_pi = reformu_pi(e, 11, cell, cstr_cell)
    noncell_pi = reformu_pi(e, 14, noncell, cstr_noncell)
    battery_pi = reformu_pi(e, 15, battery, cstr_battery)
    pi_matrix = op_pi + cth_pi + cell_pi + noncell_pi + battery_pi
    
    alp = getdual(cstr_alp)

    
    #######################
    result = Dict(["qyhat"=>qy_hat, "y_opt"=>sub_y, "s_opt"=>sub_s, "pi"=>pi_matrix, "alp"=>alp]);
    return result
    
end

subprob (generic function with 1 method)

In [256]:
function masterprob(cuts)
    model = Model(Gurobi.Optimizer)
    set_silent(model)
    @variable(model, x[1:ncty, 1:nproc] >= 0)
    @variable(model, theta >= M)
    
    for k in 1:nproc
        for i in 1:ncty
            @constraint(model, x[i,k] <= capacity[!, 2:end][i,k])
        end
    end
    
    ###########
    for i in 1:ncty
        @constraint(model, sum(x[i,k] * price[k] for k in 1:nproc) <= vGDP[i])
    end
    ###########
    
    for k in 1:nproc
        @constraint(model, sum(x[i,k] for i in 1:ncty) >= input_amount[k])
        @constraint(model, sum(x[i,k] for i in 1:ncty) <= 1.2*input_amount[k])
    end
    
    proD = (x .* Matrix(regional_EF[:,2:end])) * ones(nproc,1) 
    proM = x * price

    pro_sink = zeros(ncty, nproc)
    for k in 1:nproc
        for i in 1:ncty
#             pro_sink[i,k] = regional_EF[i, k+1] * (sink_c[i]/emission_c[i] + es_ratio)
            pro_sink[i,k] = (price[k]/vGDP[i]) * sink_c[i] + (price[k]/global_gdp) * global_sink
        end
    end
    proS = (x.*pro_sink)*ones(nproc,1) 
    
    if cuts != []
        for cut in cuts
            G = cut["gradient"]
            g = cut["intersection"]
            @constraint(model, sum(x .* G) + theta >= g)
        end
    end
    
    @objective(model, Min, sum(proD-proS)+theta)
    JuMP.optimize!(model);
    
    x_hat = JuMP.value.(x)
    theta_hat = JuMP.value.(theta)
    z_lb = JuMP.objective_value(model)
    
    result = Dict(["x_hat"=>x_hat, "z_lb"=>z_lb])
    return result
end

masterprob (generic function with 1 method)

In [257]:
function add_cuts(x, D)
    G = [] # gradient
    g = 0 # intersection
    qy = 0
    
    for e in D
        res = subprob(x, e)
        gradient = -1 * res["pi"]
        
        push!(G, gradient)
        g += cell_demand * res["alp"]
        qy += res["qyhat"]
    end
    
    proD = (x .* Matrix(regional_EF[:,2:end])) * ones(nproc,1) 
    pro_sink = zeros(ncty, nproc)
    for k in 1:nproc
        for i in 1:ncty
#             pro_sink[i,k] = regional_EF[i, k+1] * (sink_c[i]/emission_c[i] + es_ratio)
            pro_sink[i,k] = (price[k]/vGDP[i]) * sink_c[i] + (price[k]/global_gdp) * global_sink
        end
    end
    proS = (x.*pro_sink)*ones(nproc,1) 
    z_hat = sum(proD - proS) + qy/size(D)[1]
    Exp_G = sum(G) / size(D)[1]
    Exp_g = sum(g) / size(D)[1]
    
    cut = Dict(["gradient"=>Exp_G, "intersection"=>Exp_g])
    return cut, z_hat
end


add_cuts (generic function with 1 method)

In [258]:
function main(toler)
    i = 0
    z_ub = 1e8
    x_opt = 0
    
    cuts = []
    res0 = masterprob(cuts)
    x_hat = res0["x_hat"]
    z_lb = res0["z_lb"]
    
    while (z_ub - z_lb) > toler * min(abs(z_ub), abs(z_lb))
        new_cut, z_hat = add_cuts(x_hat, D)
        if z_hat < z_ub
            z_ub = z_hat
            x_opt = x_hat
        end
        
        push!(cuts, new_cut)
        
        res1 = masterprob(cuts)
        z_lb = res1["z_lb"]
        x_hat = res1["x_hat"]
        
        i += 1
    end
    
    result = Dict(["z_lb"=>z_lb, "z_ub"=>z_ub, "x_opt"=>x_opt, "iteration"=>i])
    return result
#     println(z_lb, z_ub, x_opt, i)
    
end

main (generic function with 2 methods)

In [259]:
RES = main(0.001)

Academic license - for non-commercial use only - expires 2023-11-27
Academic license - for non-commercial use only - expires 2023-11-27
Academic license - for non-commercial use only - expires 2023-11-27
Academic license - for non-commercial use only - expires 2023-11-27
Academic license - for non-commercial use only - expires 2023-11-27
Academic license - for non-commercial use only - expires 2023-11-27
Academic license - for non-commercial use only - expires 2023-11-27
Academic license - for non-commercial use only - expires 2023-11-27


Dict{String, Any} with 4 entries:
  "z_lb"      => -1.83131e8
  "x_opt"     => [6200.0 0.0 … 0.0 0.0; 11704.3 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.…
  "iteration" => 1
  "z_ub"      => -1.83108e8

In [262]:
optx_sto = RES["x_opt"]

res_x = DataFrame(optx_sto, :auto)
rename!(res_x, ["x$i" => proc for (i, proc) in enumerate(process)])
insertcols!(res_x, 1, :country => countries)

30×16 DataFrame
 Row │ country               Li       Co       Mn       Ni       cathode    gr ⋯
     │ String                Float64  Float64  Float64  Float64  Float64    Fl ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ Argentina              6200.0      0.0      0.0      0.0  0.0           ⋯
   2 │ Australia             11704.3      0.0      0.0      0.0  0.0
   3 │ Brazil                 2200.0      0.0  67696.8  67000.0  0.0         8
   4 │ Canada                  500.0      0.0      0.0      0.0  0.0
   5 │ Chile                 39000.0      0.0      0.0      0.0  0.0           ⋯
   6 │ China                     0.0      0.0      0.0      0.0  0.0
   7 │ Colombia                  0.0      0.0      0.0  16259.3  0.0
   8 │ Congo                     0.0  83415.0      0.0      0.0  0.0
   9 │ Finland                   0.0      0.0      0.0      0.0  0.0           ⋯
  10 │ France                    0.0      0.0      0.0      0.0  1.29687e5
  11 │ Germany                   0.0      0.0      0.0      0.0  0.0
  ⋮  │          ⋮               ⋮        ⋮        ⋮        ⋮         ⋮         ⋱
  21 │ Philippines               0.0      0.0      0.0      0.0  0.0
  22 │ Portugal                  0.0      0.0      0.0      0.0  0.0           ⋯
  23 │ Russia                    0.0      0.0      0.0      0.0  0.0
  24 │ Saudi arabia              0.0      0.0      0.0      0.0  0.0
  25 │ South Africa              0.0      0.0      0.0      0.0  0.0
  26 │ South korea               0.0      0.0      0.0      0.0  0.0           ⋯
  27 │ Turkey                    0.0      0.0      0.0      0.0  0.0
  28 │ Ukraine                   0.0      0.0      0.0      0.0  0.0
  29 │ United Arab Emirates      0.0      0.0      0.0      0.0  0.0
  30 │ United States             0.0      0.0      0.0      0.0  0.0           ⋯
                                                   10 columns and 9 rows omitted

In [263]:
CSV.write("/Users/bourg/Desktop/Oct31/eco_stocnew.csv", res_x) 

"/Users/bourg/Desktop/Oct31/eco_stocnew.csv"

In [247]:
RES["x_opt"]

30×15 Matrix{Float64}:
  6200.0       0.0      0.0      0.0   …     0.0   0.0        0.0
  1770.29      0.0      0.0      0.0         0.0   0.0        0.0
  2200.0       0.0  67696.8  67000.0         0.0   4.51715e5  0.0
   500.0       0.0      0.0      0.0         0.0   0.0        0.0
 39000.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0   …     0.0   0.0        0.0
     0.0       0.0      0.0   2382.78        0.0   0.0        0.0
     0.0   69512.5      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0   …     0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     ⋮                                 ⋱                      
     0.0       0.0      0.0      0.0         0.0   0.0  

In [133]:
function det_model()
    model = Model(Gurobi.Optimizer)
    @variable(model, y[1:ncty, 1:ncty, 1:nproc] >= 0)
    @variable(model, x[1:ncty, 1:nproc] >= 0)
    
    cstr_cap = [@constraint(model, x[i,k] <= capacity[!, 2:end][i,k]) for k in 1:nproc for i in 1:ncty]
    cstr_ip = [@constraint(model, sum(x[i,k] for i in 1:ncty) >= input_amount[k]) for k in 1:nproc]
    
    cstr_op = [@constraint(model, sum(y[i,j,k] for j in 1:ncty) <= x[i,k]) for k in 1:nproc for i in 1:ncty]
    cstr_cth = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,5]*scaler[k]) for k in cathode for j in 1:ncty]
    cstr_cell = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,11]*scaler[k]) for k in cell for j in 1:ncty]
    cstr_noncell = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,14]*scaler[k]) for k in noncell for j in 1:ncty]
    cstr_battery = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,15]*scaler[k]) for k in battery for j in 1:ncty]
    @constraint(model, sum(y[i,mkt_loc,mkt_proc] for i in 1:ncty) >= cell_demand)
    for j in 1:ncty-1
        @constraint(model, sum(y[i,j,mkt_proc] for i in 1:ncty) == 0)
    end
    
    ############################
    proD = (x .* Matrix(regional_EF[:,2:end])) * ones(nproc,1) 
    proM = x * price

    pro_sink = zeros(ncty, nproc)
    for k in 1:nproc
        for i in 1:ncty
            pro_sink[i,k] = regional_EF[i, k+1] * (sink_c[i]/emission_c[i] + es_ratio)
        end
    end
    proS = (x.*pro_sink)*ones(nproc,1) 
    
    ###
    proD = (x .* Matrix(regional_EF[:,2:end])) * ones(nproc,1) 
    proM = x * price

    pro_sink = zeros(ncty, nproc)
    for k in 1:nproc
        for i in 1:ncty
            pro_sink[i,k] = regional_EF[i, k+1] * (sink_c[i]/emission_c[i] + es_ratio)
        end
    end
    proS = (x.*pro_sink)*ones(nproc,1) 
    #######
    
    tranD = Vector{AffExpr}(undef, ncty)
    tranS= Vector{AffExpr}(undef, ncty)
    for j in 1:ncty
        arc_emi = 0
        for i in 1:ncty
            amount = sum(y[i,j,k] for k in 1:nproc)
            arc_emi += (amount * distance[!, 2:end][i,j] * EF_trans)
        end
        tranD[j] = arc_emi
        tranS[j] = arc_emi * (sink_c[j]/emission_c[j] + es_ratio)
    end

    Allo_soc = (proD+tranD) ./ emission_c .* Dsoc

    vec_S = proS + tranS
    vec_D = proD + tranD
    
    @objective(model, Min, sum(vec_D-vec_S))
    JuMP.optimize!(model)
    
    opt_x = JuMP.value.(x)
    opt_y = JuMP.value.(y)
    opt_obj = JuMP.objective_value(model)
    
    result = Dict(["opt_x"=>opt_x, "opt_obj"=>opt_obj, "opt_y"=>opt_y])
    
    return result
    
end

det_model (generic function with 1 method)

In [231]:
function det_model_price()
    model = Model(Gurobi.Optimizer)
    @variable(model, y[1:ncty, 1:ncty, 1:nproc] >= 0)
    @variable(model, x[1:ncty, 1:nproc] >= 0)
    
    cstr_cap = [@constraint(model, x[i,k] <= capacity[!, 2:end][i,k]) for k in 1:nproc for i in 1:ncty]
    for i in 1:ncty
        @constraint(model, sum(x[i,k] * price[k] for k in 1:nproc) <= vGDP[i])
    end
    
    cstr_ip = [@constraint(model, sum(x[i,k] for i in 1:ncty) == input_amount[k]) for k in 1:nproc]
    
    cstr_op = [@constraint(model, sum(y[i,j,k] for j in 1:ncty) <= x[i,k]) for k in 1:nproc for i in 1:ncty]
    cstr_cth = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,5]*scaler[k]) for k in cathode for j in 1:ncty]
    cstr_cell = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,11]*scaler[k]) for k in cell for j in 1:ncty]
    cstr_noncell = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,14]*scaler[k]) for k in noncell for j in 1:ncty]
    cstr_battery = [@constraint(model, sum(y[i,j,k] for i in 1:ncty) <= x[j,15]*scaler[k]) for k in battery for j in 1:ncty]
    @constraint(model, sum(y[i,mkt_loc,mkt_proc] for i in 1:ncty) >= cell_demand)
    for j in 1:ncty-1
        @constraint(model, sum(y[i,j,mkt_proc] for i in 1:ncty) == 0)
    end
    
    ############################
    proD = (x .* Matrix(regional_EF[:,2:end])) * ones(nproc,1) 
    proM = x * price

    pro_sink = zeros(ncty, nproc)
    for k in 1:nproc
        for i in 1:ncty
            pro_sink[i,k] = (price[k]/vGDP[i]) * sink_c[i] + (price[k]/global_gdp) * global_sink
        end
    end
    proS = (x.*pro_sink)*ones(nproc,1) 
    
    #######
    
    tranD = Vector{AffExpr}(undef, ncty)
    for j in 1:ncty
        arc_emi = 0
        for i in 1:ncty
            amount = sum(y[i,j,k] for k in 1:nproc)
            arc_emi += (amount * distance[!, 2:end][i,j] * EF_trans)
        end
        tranD[j] = arc_emi
    end

    vec_S = proS
    vec_D = proD + tranD
    
    @objective(model, Min, sum(vec_D-vec_S))
    JuMP.optimize!(model)
    
    opt_x = JuMP.value.(x)
    opt_y = JuMP.value.(y)
    opt_obj = JuMP.objective_value(model)
    
    result = Dict(["opt_x"=>opt_x, "opt_obj"=>opt_obj, "opt_y"=>opt_y])
    
    return result
    
end

det_model_price (generic function with 1 method)

In [234]:
tt = det_model_price()
ttt = tt["opt_x"]
# sum(ttt[:,14])

Academic license - for non-commercial use only - expires 2023-11-27
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 1395 rows, 13950 columns and 29220 nonzeros
Model fingerprint: 0x4c8b4056
Coefficient statistics:
  Matrix range     [4e-03, 6e+05]
  Objective range  [5e-02, 2e+04]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+02, 2e+13]
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.
Presolve removed 1390 rows and 13943 columns
Presolve time: 0.00s
Presolved: 5 rows, 7 columns, 14 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -1.5310844e+08   3.750000e-04   0.000000e+00      0s
       3   -1.5310844e+08   0.000000e+00   0.000000e+00      0s

Solved in 3 iterations and 0.01 seconds
Optimal objective -1.531084432e+08

User-callback calls 43, time in user-callback 0.00 sec


30×15 Matrix{Float64}:
  6200.0       0.0      0.0      0.0   …     0.0   0.0        0.0
  1770.29      0.0      0.0      0.0         0.0   0.0        0.0
  2200.0       0.0  67696.8  67000.0         0.0   4.51715e5  0.0
   500.0       0.0      0.0      0.0         0.0   0.0        0.0
 39000.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0   …     0.0   0.0        0.0
     0.0       0.0      0.0   2382.78        0.0   0.0        0.0
     0.0   69512.5      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0   …     0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     0.0       0.0      0.0      0.0         0.0   0.0        0.0
     ⋮                                 ⋱                      
     0.0       0.0      0.0      0.0         0.0   0.0  

In [187]:
input_amount

15-element Vector{Float64}:
  49670.291589732
  69512.470736544
  67696.846500888
  69382.78329114
 129687.44540400001
  72376.074329
   5239.896784
   1309.974196
  31111.887154999997
  60258.81301599999
 327493.549
   2258.5762
   1806.86096
 451715.24
 451715.24

In [136]:
res = det_model()

Academic license - for non-commercial use only - expires 2023-11-27
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 1365 rows, 13950 columns and 28770 nonzeros
Model fingerprint: 0x4465a02d
Coefficient statistics:
  Matrix range     [4e-03, 1e+00]
  Objective range  [7e-03, 3e+02]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+02, 1e+11]
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.
Presolve removed 1323 rows and 13825 columns
Presolve time: 0.01s
Presolved: 42 rows, 125 columns, 228 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -6.1432517e+08   2.021935e+05   0.000000e+00      0s
Extra simplex iterations after uncrush: 18
      50   -6.1255008e+08   0.000000e+00   0.000000e+00      0s

Solved in 50 iterations and 0.01 seconds
Optimal objective -6.125500774e+08

User-call

Dict{String, Any} with 3 entries:
  "opt_y"   => [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.…
  "opt_obj" => -6.1255e8
  "opt_x"   => [6200.0 0.0 … 0.0 0.0; 61000.0 7000.0 … 1.0e6 0.0; … ; 0.0 0.0 ……

In [158]:
det = res["opt_x"] 
sto = RES["x_opt"];

In [159]:
for i in 1:15
    if det[:,i] != sto[:, i]
        println(i)
    end
end

12


In [160]:
det[:,12] == sto[:,12]

false

In [161]:
for i in 1:30
    if det[i,12] != sto[i,12]
        println(i)
    end
end

18


In [162]:
 det[18,12]

5000.0

In [163]:
sto[18,12]

0.0