In [1]:
using JuMP, Gurobi
using CSV, LinearAlgebra, DataFrames

In [2]:
#load the data and orgnize 
FL = repeat([Float64], inner=15)
dtype = append!([String], FL);

regional_EF = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/new_EF_SC1.csv",header=1,delim=",", types=dtype) |> DataFrame    
capacity = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/capacity2.csv",header=1,delim=",", types=dtype) |> DataFrame    
distance = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/distance.csv",header=1,delim=",") |> DataFrame 
LCA_model = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/LCA_model2.csv",header=1,delim=",") |> DataFrame 
D_Dsoc = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/D_Dsoc1.csv",header=1,delim=",") |> DataFrame
GDP = CSV.File("C:/Users/bourg/.julia/environments/batterySC/Li-battery-SC/data/social/GDP.csv",header=1,delim=",") |> DataFrame;

In [3]:
cell_demand = 0.001*164.98*(1.3*1e6)*2           # annual demand of Li battery for tesla (1.369M EV/yr, ~2 NMC111 pack/EV, 226 kg/pack (35kwh/pack), 80~100 kWh per EV)

D = D_Dsoc[!, "D"]          # national CO2 emission (ton/yr)
Dsoc = D_Dsoc[!, "Dsoc ton/yr"]           # national CO2 sink (ton/yr)

EF_trans = 1.005/10000                        # ton CO2/km*ton (The average freight truck in the U.S. emits 161.8 grams of CO2 per ton-mile)
process = LCA_model[!,"process"]
countries = capacity[!,"country"]
ncty = size(countries,1)                          # No. of countries
nproc = size(process,1);                          # No. of processes 

mkt_loc = findfirst(isequal("United States"), countries)
mkt_proc = findfirst(isequal("battery"), process)

# seperate model
cathode = 1:4
cell = 5:10
noncell = [12,13]
battery = [11,14]
scaler = LCA_model[!,"scaler"]
price = LCA_model[!,"price (usd/ton product)"]
vGDP = GDP[!,"GDP usd"];

In [5]:
up_cath = scaler[1:4] * scaler[5] * scaler[11]
up_cell = scaler[5:10] * scaler[11]
cell_sef = scaler[11]
up_noncell = scaler[12:13] * scaler[14]
noncell_sef = scaler[14]
battery_sef = scaler[15]

1.0

In [7]:
input_amount = []
input_amount = vcat(up_cath, up_cell, cell_sef, up_noncell, noncell_sef, battery_sef) .* cell_demand
input_amount  # ton

15-element Vector{Float64}:
  47166.82181639999
  66008.92034879999
  64284.806757599996
  65885.769378
 123150.9708
  68728.1933
   4975.796799999999
   1243.9491999999998
  29543.793499999992
  57221.66319999999
 310987.29999999993
   2144.74
   1715.792
 428947.99999999994
 428947.99999999994

In [8]:
MktV = price .* input_amount 

15-element Vector{Float64}:
 1.8866728726559997e9
 5.247709167729599e9
 9.707005820397599e7
 1.32628053757914e9
 9.1131718392e8
 1.374563866e9
 6.010762534399999e6
 1.4218339355999997e6
 2.4255454463499993e8
 1.2228269425839998e8
 8.521052019999998e9
 2.8953989999999995e6
 1.0294752e9
 1.5056074799999998e9
 1.0037383199999998e10

In [9]:
maximum(MktV)

1.0037383199999998e10

In [10]:
minimum(vGDP)

5.54e10

----

In [65]:
model = Model(Gurobi.Optimizer);

Academic license - for non-commercial use only - expires 2023-11-27


In [66]:
#variables 
@variable(model, x[1:ncty, 1:nproc] >= 0)            # x[i,k] production amount of product k at location i
@variable(model, y[1:ncty, 1:ncty, 1:nproc] >= 0)   # y[i,j,k] ship product k from i to j 
@variable(model, delta[1:ncty], binary=true);

In [67]:
# capacity constraint: x[i,k] <= capacity[i][k]
for k in 1:nproc
    for i in 1:ncty
        @constraint(model, x[i,k] <= capacity[!, 2:end][i,k])
    end
end

In [68]:
# node output flow constraint
for k in 1:nproc
    for i in 1:ncty
        @constraint(model, sum(y[i,j,k] for j in 1:ncty) == x[i,k])
    end
end

In [69]:
# node output flow to market y[i,38, 15]
for i in 1:ncty
    for j in [e for e in 1:ncty if e != mkt_loc]
        @constraint(model, y[i,j,mkt_proc] == 0)
    end
end

In [70]:
for k in 1:nproc-1
    @constraint(model, sum(x[i,k] for i in 1:ncty) == input_amount[k])
end

In [71]:
# final demand constraint
@constraint(model, sum(y[i,mkt_loc,mkt_proc] for i in 1:ncty) == cell_demand);

In [72]:
# cathode LCA constraints (index=5)
for k in cathode
    for j in 1:ncty
        @constraint(model, sum(y[i,j,k] for i in 1:ncty) == x[j,5] * scaler[k])
    end
end


# cell LCA constraints (index=11)
for k in cell
    for j in 1:ncty
        @constraint(model, sum(y[i,j,k] for i in 1:ncty) == x[j,11] * scaler[k])
    end
end


# non cell LCA constraints (index=14)
for k in noncell
    for j in 1:ncty
        @constraint(model, sum(y[i,j,k] for i in 1:ncty) == x[j,14] * scaler[k])
    end
end


# battery LCA constraints (index=15)
for k in battery
    for j in 1:ncty
        @constraint(model, sum(y[i,j,k] for i in 1:ncty) == x[j,15] * scaler[k])
    end
end


In [73]:
Pemi = 0
Pincome = 0
proD = Vector{AffExpr}(undef, ncty)
proM = Vector{AffExpr}(undef, ncty)

for i in 1:ncty
    for k in 1:nproc
        Pemi += regional_EF[i,k+1] * x[i,k]
        Pincome += x[i,k] * price[k]
    end
    proD[i] = Pemi
    proM[i] = Pincome
end


Temi = 0
transD = Vector{AffExpr}(undef, ncty)
for i in 1:ncty
    for j in 1:ncty
        amount = sum(y[i,j,k] for k in 1:nproc)
        Temi += amount * distance[!, 2:end][i,j] * EF_trans
    end
    transD[i] = Temi
end

In [74]:
proM[1]

40000 x[1,1] + 79500 x[1,2] + 1510 x[1,3] + 20130 x[1,4] + 7400 x[1,5] + 20000 x[1,6] + 1208 x[1,7] + 1143 x[1,8] + 8210 x[1,9] + 2137 x[1,10] + 27400 x[1,11] + 1350 x[1,12] + 600000 x[1,13] + 3510 x[1,14] + 23400 x[1,15]

In [75]:
for i in 1:ncty
    @constraint(model, proM[i] <= vGDP[i])
end

In [76]:
M = 1e20
Allo_soc = proM ./ vGDP .* Dsoc
SJ = proD + transD - Allo_soc;

In [77]:
for i in 1:ncty
    @constraint(model, SJ[i] >= (delta[i] - 1) * M)
end

for i in 1:ncty
    @constraint(model, SJ[i] <= delta[i] * M)
end

In [78]:
@objective(model, Max, sum(delta));

In [79]:
JuMP.optimize!(model)

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads
Optimize a model with 2295 rows, 13980 columns and 454275 nonzeros
Model fingerprint: 0xb69fd17e
Variable types: 13950 continuous, 30 integer (30 binary)
Coefficient statistics:
  Matrix range     [2e-04, 1e+20]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+02, 1e+20]
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.
Presolve removed 2295 rows and 13980 columns
Presolve time: 0.04s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.14 seconds
Thread count was 1 (of 12 available processors)

Solution count 1: 30 

Optimal solution found (tolerance 1.00e-04)
         (possibly due to large matrix coefficients)
Best objective 3.000000000000e+01, best bound 3.000000000000e+01, gap 0.0000%

User-callback calls 135, time in us

In [26]:
JuMP.value.(x)

30×15 Matrix{Float64}:
     0.0      0.0      0.0      0.0  …     0.0     0.0         0.0      0.0
 47166.8      0.0      0.0      0.0        0.0     0.0         0.0      0.0
     0.0      0.0      0.0      0.0        0.0     0.0         0.0      0.0
     0.0      0.0      0.0      0.0     2144.74    0.0         0.0      0.0
     0.0      0.0      0.0      0.0        0.0     0.0         0.0      0.0
     0.0      0.0      0.0      0.0  …     0.0     0.0         0.0  85789.6
     0.0      0.0      0.0      0.0        0.0     0.0         0.0      0.0
     0.0  66008.9      0.0      0.0        0.0     0.0         0.0      0.0
     0.0      0.0      0.0      0.0        0.0     0.0         0.0      0.0
     0.0      0.0      0.0      0.0        0.0     0.0         0.0      0.0
     0.0      0.0      0.0      0.0  …     0.0     0.0         0.0  85789.6
     0.0      0.0      0.0      0.0        0.0     0.0         0.0      0.0
     0.0      0.0      0.0  21961.9        0.0     0.0    214474.

In [27]:
optx = copy(JuMP.value.(x))
opty = copy(JuMP.value.(y));

In [28]:
res_x = DataFrame(optx, :auto)
rename!(res_x, ["x$i" => proc for (i, proc) in enumerate(process)])
insertcols!(res_x, 1, :country => countries);

In [59]:
# DataFrame(opty[1:end, 1:end, 1], :auto)

In [29]:
CSV.write("/Users/bourg/Desktop/x_matrix_0915_worst.csv", res_x) 

"/Users/bourg/Desktop/x_matrix_0915_worst.csv"

----

In [37]:
Pemi = 0
Pincome = 0
proD = zeros(ncty)
proM = zeros(ncty)

for i in 1:ncty
    for k in 1:nproc
        Pemi += regional_EF[i,k+1] * optx[i,k]
        Pincome += optx[i,k] * price[k]
    end
    proD[i] = Pemi
    proM[i] = Pincome
end

In [39]:
Temi = 0
transD = zeros(ncty)
for i in 1:ncty
    for j in 1:ncty
        amount = sum(opty[i,j,k] for k in 1:nproc)
        Temi += amount * distance[!, 2:end][i,j] * EF_trans
    end
    transD[i] = Temi
end

In [41]:
Allo_soc = proM ./ vGDP .* Dsoc;

In [42]:
SJ = proD + transD - Allo_soc

30-element Vector{Float64}:
       0.0
  146302.13332199663
  123831.42101741045
  206256.08675930544
  159912.63574448245
       1.056562300404097e6
  875207.1441314534
 -794987.1116928686
       2.924519861638376e6
       3.0915770757717355e6
       3.950255987924516e6
  615154.6924511166
       3.1179878368311003e6
       ⋮
       5.53059013545199e6
       4.554944546771766e6
       3.2063561278521023e6
       5.516343264027968e6
      -9.0869063574939e8
      -3.938191876841539e8
       4.066881103618127e6
      -5.091918499342205e8
       6.573037055059096e6
       5.237567647721427e6
       7.624298300202082e6
       1.0146016860700918e7

In [45]:
optdelta = JuMP.value.(delta);

In [49]:
SJ[2]

146302.13332199663

In [48]:
(optdelta[2] - 1) * M

-1.0e20

In [31]:
# using Tables
# res = Tables.table(optx[1:end, 1:end]);
# CSV.write("/Users/bourg/Desktop/x_matrix_regional0914.csv", res) 

In [30]:
# res_y02 = Tables.table(opty[1:end, 1:end, 02])
# CSV.write("/Users/bourg/Desktop/y02_matrix.csv", res_y02) 